export const COUNTRY_LIST = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "Germany",
  "France",
  "Spain",
  "Italy",
  "Netherlands",
  "Belgium",
  "Portugal",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Ireland",
  "Poland",
  "Czech Republic",
  "Austria",
  "Switzerland",
  "India",
  "China",
  "Japan",
  "South Korea",
  "Singapore",
  "Hong Kong",
  "United Arab Emirates",
  "Saudi Arabia",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Ghana",
  "Egypt",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "New Zealand",
];

export const CITY_MAP: Record<string, string[]> = {
  "United States": ["New York", "Los Angeles", "Chicago", "Houston", "Miami", "San Francisco", "Seattle", "Boston", "Dallas", "Atlanta"],
  Canada: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa"],
  "United Kingdom": ["London", "Manchester", "Birmingham", "Leeds", "Glasgow"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  Germany: ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne"],
  France: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice"],
  Spain: ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza"],
  Italy: ["Rome", "Milan", "Naples", "Turin", "Florence"],
  Netherlands: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
  Belgium: ["Brussels", "Antwerp", "Ghent", "Bruges", "Liège"],
  Portugal: ["Lisbon", "Porto", "Braga", "Coimbra", "Faro"],
  Sweden: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås"],
  Norway: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Tromsø"],
  Denmark: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  Finland: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu"],
  Ireland: ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
  Poland: ["Warsaw", "Krakow", "Wroclaw", "Poznan", "Gdansk"],
  "Czech Republic": ["Prague", "Brno", "Ostrava", "Plzen", "Liberec"],
  Austria: ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck"],
  Switzerland: ["Zurich", "Geneva", "Basel", "Lausanne", "Bern"],
  India: ["Mumbai", "Delhi", "Bengaluru", "Chennai", "Kolkata", "Hyderabad"],
  China: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu"],
  Japan: ["Tokyo", "Osaka", "Nagoya", "Sapporo", "Fukuoka"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
  Singapore: ["Singapore"],
  "Hong Kong": ["Hong Kong"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"],
  "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth"],
  Nigeria: ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt"],
  Kenya: ["Nairobi", "Mombasa", "Kisumu", "Eldoret", "Nakuru"],
  Ghana: ["Accra", "Kumasi", "Tamale", "Takoradi", "Cape Coast"],
  Egypt: ["Cairo", "Alexandria", "Giza", "Luxor", "Aswan"],
  Brazil: ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador", "Fortaleza"],
  Mexico: ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana"],
  Argentina: ["Buenos Aires", "Cordoba", "Rosario", "Mendoza", "La Plata"],
  Chile: ["Santiago", "Valparaiso", "Concepcion", "Antofagasta", "Temuco"],
  Colombia: ["Bogota", "Medellin", "Cali", "Barranquilla", "Cartagena"],
  Peru: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Cusco"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Dunedin"],
};
